services:
  coesi-model-manager-backend:
    build: .
    container_name: coesi-model-manager-backend
    ports:
      - "8080:8080"
    volumes:
      - ./dummy-format-1.json:/app/dummy-format-1.json
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
