name: CI/CD Pipelines
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull changes and restart container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set -e
            cd ${{ secrets.APP_DIRECTORY }} &&
            git reset --hard HEAD &&
            git pull origin main &&
            sudo docker compose -f ${{ secrets.DOCKER_COMPOSE_PROD_FILE }} build &&
            sudo docker compose -f ${{ secrets.DOCKER_COMPOSE_PROD_FILE }} up -d
          "

      - name: Verify deployment
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            sudo docker ps
          "
